# Generated by Django 6.0.3 on 2026-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
